{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-application.fullname" . }}
  labels:
    {{- include "generic-application.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "generic-application.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
...
{{- end }}
